# Generated by Django 5.2.8 on 2025-12-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
