###
POST  http://127.0.0.1:8020/api/auth/register/
Content-Type: application/json 

{
    "email":"anmamun0@gmail.com",
    "password": "123",
    "confirm_password": "123",
    "role":"customer"
}

###
POST  http://127.0.0.1:8020/api/auth/login/
Content-Type: application/json 

{
    "email":"anmamun2@gmail.com",
    "password": "123" 
}

###
POST  http://127.0.0.1:8020/api/auth/login/refresh/
Content-Type: application/json 

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NzQxNjYzNCwiaWF0IjoxNzY0ODI0NjM0LCJqdGkiOiJlZWZjODIwYjQ2MmU0ZWQwYmVmOTMyZGFmZGVjMmZmOCIsInVzZXJuYW1lIjoiYW5tYW11bjIiLCJlbWFpbCI6ImFubWFtdW4yQGdtYWlsLmNvbSIsInJvbGUiOiJzaG9wX293bmVyIiwidXNlcl9pZCI6ImE5ZGE4MTg2LTA0NGQtNDhlNi05NDQ0LWQyYzI5ZTgxNGY0MCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfQ.6G06kprymphHyloJLsT4A38ASafUw7sfGhzHJ660ZnY"
}

###
DELETE   http://127.0.0.1:8020/api/auth/profile/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDI5NTQ5LCJpYXQiOjE3NjQ4MjQ3NDksImp0aSI6ImUzODMxZTIxYmZkNzQ0YzNhZTI1ZjZiZDE5YzU5OWViIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9.AhmEyPLESq5PepdR1JQGOPl4f5HSRbZpRA4v64UpRRY
Content-Type: application/json 

{
  "username": "anmamun2" ,
  "email":"anmamun2@gmail.com" 

}


###
POST  http://127.0.0.1:8020/api/auth/email/resend/otp/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDMzMzk3LCJpYXQiOjE3NjQ4Mjg1OTcsImp0aSI6IjlhNGJmZWY5ZTMzZDRlOGZiZDQxNjdlMjg5N2Y3YWMyIiwidXNlcm5hbWUiOiJhbm1hbXVuMCIsImVtYWlsIjoiYW5tYW11bjBAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwidXNlcl9pZCI6IjM1Njg3ZGFhLTU5YzctNDA2NC04MmU5LTNiZWI0N2U4MzNiYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZX0.8PqLySz5TQ3b5r3SPDEJ9xoU-BfWn3lnS-7NjVduzP8
Content-Type: application/json 

{ 
  "email":"anmamun0@gmail.com" 

}
 
###
POST  http://127.0.0.1:8020/api/auth/email/verify/otp/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NDMzMzk3LCJpYXQiOjE3NjQ4Mjg1OTcsImp0aSI6IjlhNGJmZWY5ZTMzZDRlOGZiZDQxNjdlMjg5N2Y3YWMyIiwidXNlcm5hbWUiOiJhbm1hbXVuMCIsImVtYWlsIjoiYW5tYW11bjBAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwidXNlcl9pZCI6IjM1Njg3ZGFhLTU5YzctNDA2NC04MmU5LTNiZWI0N2U4MzNiYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZX0.8PqLySz5TQ3b5r3SPDEJ9xoU-BfWn3lnS-7NjVduzP8
Content-Type: application/json 

{ 
  "email":"anmamun0@gmail.com" ,
  "otp":"441138" 

}


###
GET  http://127.0.0.1:8020/api/store/shop/
 

###
GET http://127.0.0.1:8020/api/store/shop/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg


###
PATCH http://127.0.0.1:8020/api/store/shop/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg
Content-Type: application/json 

{ 
  "is_active": false
}

###
GET  http://127.0.0.1:8020/api/store/category/

###
GET  http://127.0.0.1:8020/api/store/category/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg

###
PATCH  http://127.0.0.1:8020/api/store/category/ace17e98-3ba2-4b8c-a943-559ea3d2071c/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg
Content-Type: application/json 

{ 
 "parent": "46852ef6-8b94-4cd4-bec2-029f8816cafb" 
}


###
GET  http://127.0.0.1:8020/api/store/products/

###
GET  http://127.0.0.1:8020/api/store/products/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg


###
PATCH  http://127.0.0.1:8020/api/store/products/e27eb7c3-4615-41b7-9f0f-50eea6f07ad3/
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1NjQwNjI5LCJpYXQiOjE3NjUwMzU4MjksImp0aSI6IjA4MGU1MTM3MTMwMTQyNjQ5OTk1YmE0MzQ1ZjA3YmNmIiwidXNlcm5hbWUiOiJhbm1hbXVuMiIsImVtYWlsIjoiYW5tYW11bjJAZ21haWwuY29tIiwicm9sZSI6InNob3Bfb3duZXIiLCJ1c2VyX2lkIjoiYTlkYTgxODYtMDQ0ZC00OGU2LTk0NDQtZDJjMjllODE0ZjQwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlfQ.pFghqthHgZznhzhAU8xfiDO4U6S7fwHCIoHySfk2mbg
Content-Type: application/json 

{ 
 "name": "ASUS Leptop 2" 
}
