# Generated by Django 5.2.8 on 2026-01-01 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_shop_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification')], default='push', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Active'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('media', models.ImageField(blank=True, null=True, upload_to='template_media/')),
                ('footer', models.CharField(blank=True, max_length=200, null=True)),
                ('button', models.JSONField(blank=True, default=dict, help_text='\n        Example:\n        {\n            "name": "View Order",\n            "url": "https://example.com/order/123"\n        }\n        ', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_messages', to='store.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_to', models.CharField(choices=[('all', 'All Customers'), ('selected', 'Selected Customers'), ('segment', 'Customer Segment')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('customers', models.ManyToManyField(blank=True, related_name='message_campaigns', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_campaigns', to='store.shop')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='messaging.templatemessage')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.messagecampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'customer'), name='unique_campaign_and_customer')],
            },
        ),
        migrations.AddIndex(
            model_name='templatemessage',
            index=models.Index(fields=['shop'], name='messaging_t_shop_id_6da4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='templatemessage',
            index=models.Index(fields=['message_type', 'status'], name='messaging_t_message_f8ff2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='templatemessage',
            constraint=models.UniqueConstraint(fields=('shop', 'title'), name='unique_shop_template_title'),
        ),
        migrations.AddIndex(
            model_name='messagecampaign',
            index=models.Index(fields=['scheduled_at'], name='messaging_m_schedul_f75680_idx'),
        ),
        migrations.AddIndex(
            model_name='messagecampaign',
            index=models.Index(fields=['is_sent'], name='messaging_m_is_sent_847e5e_idx'),
        ),
    ]
