# Generated by Django 5.2.8 on 2026-01-01 14:50

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Plan name e.g. Basic, Pro', max_length=100)),
                ('description', models.TextField(help_text='Feature Description write saparately with comma')),
                ('send_to', models.CharField(choices=[('all', 'All Customers'), ('selected', 'Selected Customers'), ('segment', 'Customer Segment')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=6)),
                ('cost_per_message', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=6)),
                ('daily_limit', models.PositiveIntegerField(default=1000, help_text='Max messages shop can send per day')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('send_to', 'is_active'), name='only_one_active_send_method')],
            },
        ),
    ]
