# Generated by Django 5.2.8 on 2026-01-01 20:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageplan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='templatemessage',
            name='unique_shop_template_title',
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='snapshot_cost_per_message',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='snapshot_recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='snapshot_total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
