# Generated by Django 5.2.8 on 2026-01-02 12:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_templatemessage_unique_shop_template_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='snapshot_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='snapshot_cost_per_message',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='snapshot_recipient_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='snapshot_total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
    ]
