# Generated by Django 5.2.8 on 2026-01-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messagecampaign_snapshot_channel_and_more'),
        ('store', '0006_alter_shop_balance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='templatemessage',
            name='messaging_t_message_f8ff2f_idx',
        ),
        migrations.RenameField(
            model_name='messagecampaign',
            old_name='snapshot_channel',
            new_name='channel_to',
        ),
        migrations.RenameField(
            model_name='templatemessage',
            old_name='message_type',
            new_name='channel_to',
        ),
        migrations.AddField(
            model_name='messageplan',
            name='channel_to',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification')], default='push', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='templatemessage',
            index=models.Index(fields=['channel_to', 'status'], name='messaging_t_channel_e47ebe_idx'),
        ),
    ]
