# Generated by Django 5.2.8 on 2026-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_remove_templatemessage_messaging_t_message_f8ff2f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messageplan',
            name='only_one_active_send_method',
        ),
        migrations.AddConstraint(
            model_name='messageplan',
            constraint=models.UniqueConstraint(fields=('send_to', 'is_active', 'channel_to'), name='only_one_active_send_method'),
        ),
    ]
