# Generated by Django 5.2.8 on 2026-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_messageplan_only_one_active_send_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='body',
            field=models.TextField(),
        ),
    ]
