# Generated by Django 5.2.8 on 2025-12-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='balance',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
