# Generated by Django 5.2.8 on 2026-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_sku_alter_productvariant_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
