# Generated by Django 5.2.8 on 2025-12-14 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankAccount',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_holder_type', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('merchant', 'Merchant')], max_length=10)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('merchant', 'Merchant')], max_length=10)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('receipt', models.ImageField(upload_to='topups/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
