# Generated by Django 5.2.8 on 2025-12-15 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0003_topup_user_transaction_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reference',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model__in', ['order', 'topup'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('order', 'Order'), ('topup', 'Top Up')], default='order', max_length=20),
        ),
    ]
