# Generated by Django 5.2.8 on 2026-01-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0004_rename_reference_transaction_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model__in', ['order', 'topup', 'messagecampaign'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('order', 'Order'), ('topup', 'Top Up'), ('promotion', 'Promotion')], default='order', max_length=20),
        ),
    ]
