# Generated by Django 5.2.8 on 2025-12-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='wireframe',
            options={'verbose_name': 'Wireframe', 'verbose_name_plural': 'Wireframes'},
        ),
    ]
