openapi: 3.0.3
info:
  title: Order Management API - Shop Owner
  version: 1.0.0
  description: API documentation for shop owner order management system (Read-only access)
  contact:
    email: support@example.com

servers:
  - url: http://127.0.0.1:8020
    description: Local development server

security:
  - BearerAuth: []

tags:
  - name: Orders
    description: Shop owner order operations (Blocked)
  - name: Order Items
    description: Order item viewing (Read-only)

paths:
  /api/order/orders/:
    get:
      tags:
        - Orders
      summary: List all orders (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    post:
      tags:
        - Orders
      summary: Create a new order (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/order/orders/{id}/:
    get:
      tags:
        - Orders
      summary: Retrieve a specific order (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    put:
      tags:
        - Orders
      summary: Update an order (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    patch:
      tags:
        - Orders
      summary: Partial update of order (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    delete:
      tags:
        - Orders
      summary: Delete an order (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/order/items/:
    get:
      tags:
        - Order Items
      summary: List all order items (Read-only)
      description: Retrieve a list of all order items with optional filtering. Shop owners can only view order items, not modify them.
      security:
        - BearerAuth: []
      parameters:
        - name: product
          in: query
          description: Filter by product ID
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          description: Filter by item status
          schema:
            type: string
            enum:
              - pending
              - shipped
              - delivered
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderItem'
              example:
                - id: "5d6dd3d4-fcb2-4844-80db-9b26e294398a"
                  product: "short_intro"
                  created_at: "2025-12-08T00:00:00Z"
                  updated_at: "2025-12-08T00:00:00Z"
                  quantity: 10
                  subtotal_amount: "0.00"
                  product_name: "TMT 500W"
                  product_price: "55666.00"
                  product_image: null
                  status: "pending"
                  order: "0223611c-33cf-4803-b6da-c037c5f0cb0d"
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      tags:
        - Order Items
      summary: Create a new order item (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /api/order/items/{id}/:
    get:
      tags:
        - Order Items
      summary: Retrieve a specific order item (Read-only)
      description: Get details of a specific order item by ID. Shop owners can only view, not modify.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the order item
          schema:
            type: string
            format: uuid
          example: "5d6dd3d4-fcb2-4844-80db-9b26e294398a"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
              example:
                id: "5d6dd3d4-fcb2-4844-80db-9b26e294398a"
                product: "short_intro"
                created_at: "2025-12-08T00:00:00Z"
                updated_at: "2025-12-08T00:00:00Z"
                quantity: 10
                subtotal_amount: "0.00"
                product_name: "TMT 500W"
                product_price: "55666.00"
                product_image: null
                status: "pending"
                order: "0223611c-33cf-4803-b6da-c037c5f0cb0d"
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    put:
      tags:
        - Order Items
      summary: Update an order item (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    patch:
      tags:
        - Order Items
      summary: Partial update of order item (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

    delete:
      tags:
        - Order Items
      summary: Delete an order item (BLOCKED)
      description: This endpoint is blocked for shop owners. Returns 403 Forbidden.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '403':
          $ref: '#/components/responses/ForbiddenError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token authentication for shop owners

  schemas:
    OrderItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Unique identifier for the order item
        product:
          type: string
          readOnly: true
          description: Product identifier
        created_at:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp when the order item was created
        updated_at:
          type: string
          format: date-time
          readOnly: true
          description: Timestamp when the order item was last updated
        quantity:
          type: integer
          minimum: 1
          readOnly: true
          description: Quantity of the product ordered
        subtotal_amount:
          type: string
          pattern: '^\d+\.\d{2}$'
          readOnly: true
          description: Calculated as product_price * quantity
        product_name:
          type: string
          maxLength: 200
          readOnly: true
          description: Snapshot of product name at order time
        product_price:
          type: string
          pattern: '^\d+\.\d{2}$'
          readOnly: true
          description: Snapshot of product price at order time
        product_image:
          type: string
          format: uri
          nullable: true
          readOnly: true
          description: Snapshot of product image URL at order time
        status:
          type: string
          enum:
            - pending
            - shipped
            - delivered
          default: pending
          readOnly: true
          description: Current status of the order item
        order:
          type: string
          format: uuid
          readOnly: true
          description: UUID of the parent order

  responses:
    UnauthorizedError:
      description: Authentication credentials were not provided or are invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          example:
            detail: "Authentication credentials were not provided."

    ForbiddenError:
      description: You do not have permission to perform this action
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          example:
            detail: "You do not have permission to perform this action."

    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          example:
            detail: "Not found."
