# Generated by Django 5.2.8 on 2025-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_channel_created_at_alter_channel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
